Attribute VB_Name = "PublicVariable"
' ïœêîêÈåæ
Public bookName As String
Public directoryLevel As Long
Public searchDevCell As String
Public searchYearCell As String
Public insPeriodCell As String
Public devTopCell As Long
Public judgeCell As Long
Public judgeDateCell As Long
Public searchDevMasterCol As Long
Public openingSheet As String
Public openingHeadRow As Long
Public openingDevGroupCol As String
Public openingDevNumCol As String
Public openingDevNameCol As String
Public thicknessSheet As String
Public thicknessHeadRow As Long
Public thicknessDevGroupCol As String
Public thicknessDevNumCol As String
Public thicknessDevNameCol As String
Public pipingSheet As String
Public pipingHeadRow As Long
Public pipingDevNum As String
Public pipingDevNameCol As String
Public sharePipingSheet As String
Public sharePipingHeadRow As Long
Public sharePipingDevNum As String
Public sharePipingDevNameCol As String
    ' ----------NCóp----------
Public sharePiping5 As String
Public sharePiping5Sheet As String
Public sharePiping10 As String
Public sharePiping10Sheet As String
